# Generated by Django 2.2.23 on 2021-05-24 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Campaign', '0013_auto_20200601_1217'),
        ('EvalData', '0046_auto_20210127_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectAssessmentWithErrorAnnotationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('dateActivated', models.DateTimeField(blank=True, null=True, verbose_name='Date activated')),
                ('dateCompleted', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('dateRetired', models.DateTimeField(blank=True, null=True, verbose_name='Date retired')),
                ('dateModified', models.DateTimeField(blank=True, null=True, verbose_name='Date modified')),
                ('activated', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Activated?')),
                ('completed', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Completed?')),
                ('retired', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Retired?')),
                ('rawData', models.TextField(blank=True, editable=False, verbose_name='Raw data')),
                ('_str_name', models.TextField(blank=True, default='', editable=False)),
                ('requiredAnnotations', models.PositiveSmallIntegerField(help_text='(value in range=[1,50])', verbose_name='Required annotations')),
                ('batchNo', models.PositiveIntegerField(help_text='(1-based)', verbose_name='Batch number')),
                ('activatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationtask_activated_by', related_query_name='evaldata_directassessmentwitherrorannotationtasks', to=settings.AUTH_USER_MODEL, verbose_name='Activated by')),
                ('assignedTo', models.ManyToManyField(blank=True, db_index=True, help_text='(users working on this task)', related_name='evaldata_directassessmentwitherrorannotationtask_assignedTo', related_query_name='evaldata_directassessmentwitherrorannotationtasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('batchData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationtask_batchData', related_query_name='evaldata_directassessmentwitherrorannotationtasks', to='Campaign.CampaignData', verbose_name='Batch data')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationtask_campaign', related_query_name='evaldata_directassessmentwitherrorannotationtasks', to='Campaign.Campaign', verbose_name='Campaign')),
                ('completedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationtask_completed_by', related_query_name='evaldata_directassessmentwitherrorannotationtasks', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('createdBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationtask_created_by', related_query_name='evaldata_directassessmentwitherrorannotationtasks', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('items', models.ManyToManyField(related_name='evaldata_directassessmentwitherrorannotationtask_items', related_query_name='evaldata_directassessmentwitherrorannotationtasks', to='EvalData.TextPairWithDomain', verbose_name='Items')),
                ('modifiedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationtask_modified_by', related_query_name='evaldata_directassessmentwitherrorannotationtasks', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('retiredBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationtask_retired_by', related_query_name='evaldata_directassessmentwitherrorannotationtasks', to=settings.AUTH_USER_MODEL, verbose_name='Retired by')),
            ],
            options={
                'ordering': ['_str_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectAssessmentWithErrorAnnotationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('dateActivated', models.DateTimeField(blank=True, null=True, verbose_name='Date activated')),
                ('dateCompleted', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('dateRetired', models.DateTimeField(blank=True, null=True, verbose_name='Date retired')),
                ('dateModified', models.DateTimeField(blank=True, null=True, verbose_name='Date modified')),
                ('activated', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Activated?')),
                ('completed', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Completed?')),
                ('retired', models.BooleanField(blank=True, db_index=True, default=False, verbose_name='Retired?')),
                ('rawData', models.TextField(blank=True, editable=False, verbose_name='Raw data')),
                ('_str_name', models.TextField(blank=True, default='', editable=False)),
                ('score', models.PositiveSmallIntegerField(help_text='(value in range=[1,100])', verbose_name='Score')),
                ('errors', models.TextField(help_text='(0 based word indexes of errors)', verbose_name='Words with Errors')),
                ('start_time', models.FloatField(help_text='(in seconds)', verbose_name='Start time')),
                ('end_time', models.FloatField(help_text='(in seconds)', verbose_name='End time')),
                ('activatedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationresult_activated_by', related_query_name='evaldata_directassessmentwitherrorannotationresults', to=settings.AUTH_USER_MODEL, verbose_name='Activated by')),
                ('completedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationresult_completed_by', related_query_name='evaldata_directassessmentwitherrorannotationresults', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('createdBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationresult_created_by', related_query_name='evaldata_directassessmentwitherrorannotationresults', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationresult_item', related_query_name='evaldata_directassessmentwitherrorannotationresults', to='EvalData.TextPairWithDomain', verbose_name='Item')),
                ('modifiedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationresult_modified_by', related_query_name='evaldata_directassessmentwitherrorannotationresults', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('retiredBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationresult_retired_by', related_query_name='evaldata_directassessmentwitherrorannotationresults', to=settings.AUTH_USER_MODEL, verbose_name='Retired by')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaldata_directassessmentwitherrorannotationresult_task', related_query_name='evaldata_directassessmentwitherrorannotationresults', to='EvalData.DirectAssessmentWithErrorAnnotationTask', verbose_name='Task')),
            ],
            options={
                'ordering': ['_str_name'],
                'abstract': False,
            },
        ),
    ]
