# Generated by Django 2.2.23 on 2021-05-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalData', '0047_directassessmentwitherrorannotationresult_directassessmentwitherrorannotationtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directassessmentwitherrorannotationresult',
            name='errors',
        ),
        migrations.AddField(
            model_name='directassessmentwitherrorannotationresult',
            name='reference_errors',
            field=models.TextField(default='', help_text='(0 based word indexes of errors)', verbose_name='Words in reference corresponding with translation errors'),
        ),
        migrations.AddField(
            model_name='directassessmentwitherrorannotationresult',
            name='translation_errors',
            field=models.TextField(default='', help_text='(0 based word indexes of errors)', verbose_name='Words in translation corresponding with translation errors'),
        ),
    ]
